import type { EnvVarSpec } from "./types";

export const authEnv: readonly EnvVarSpec[] = [
  {
    name: "AUTH_MODE",
    group: "Authentication",
    kind: "enum",
    values: ["local", "hybrid", "oidc_enforced", "disabled", "proxy"],
    default: "local",
    doc: "Authentication mode: local credentials, hybrid, OIDC-enforced, proxy (trusted gateway sets X-Authenticated-Email; never expose the backend directly), or disabled (no login; every request runs as a single shared local user — do not expose such an instance to untrusted networks).",
  },
  {
    name: "PROXY_ADMIN_EMAIL",
    group: "Authentication",
    kind: "string",
    doc: "Required in proxy mode: the only email granted the ADMIN role; every other portal account is a USER.",
  },
  {
    name: "JWT_SECRET",
    group: "Authentication",
    kind: "string",
    secret: true,
    requiredInProduction: true,
    doc: "Secret used to sign JWTs; an ephemeral random secret is generated in dev when unset.",
    example: "change-this-secret-in-production-min-32-chars",
  },
  {
    name: "JWT_ACCESS_EXPIRES_IN",
    group: "Authentication",
    kind: "string",
    default: "15m",
    doc: "Access-token lifetime (vercel/ms style duration).",
  },
  {
    name: "JWT_REFRESH_EXPIRES_IN",
    group: "Authentication",
    kind: "string",
    default: "7d",
    doc: "Refresh-token lifetime (vercel/ms style duration).",
  },
  {
    name: "ENABLE_PASSWORD_RESET",
    group: "Authentication",
    kind: "boolean",
    default: "false",
    doc: "Enable the password-reset flow.",
  },
  {
    name: "ENABLE_REFRESH_TOKEN_ROTATION",
    group: "Authentication",
    kind: "boolean",
    default: "true",
    doc: "Rotate refresh tokens on each successful refresh.",
  },
  {
    name: "ENABLE_AUDIT_LOGGING",
    group: "Authentication",
    kind: "boolean",
    default: "false",
    doc: "Write authentication/authorization audit-log entries.",
  },
  {
    name: "DISABLE_ONBOARDING_GATE",
    group: "Authentication",
    kind: "boolean",
    default: "false",
    doc: "Disable the first-run onboarding gate in local-mode production.",
  },
  {
    name: "BOOTSTRAP_SETUP_CODE_TTL_MS",
    group: "Authentication",
    kind: "number",
    default: "900000",
    doc: "Lifetime (ms) of the initial admin bootstrap setup code.",
  },
  {
    name: "BOOTSTRAP_SETUP_CODE_MAX_ATTEMPTS",
    group: "Authentication",
    kind: "number",
    default: "10",
    doc: "Maximum verification attempts for the bootstrap setup code.",
  },
  {
    name: "PASSWORD_MIN_LENGTH",
    group: "Authentication",
    kind: "number",
    default: "12",
    doc: "Minimum accepted password length.",
  },
  {
    name: "PASSWORD_MAX_LENGTH",
    group: "Authentication",
    kind: "number",
    default: "100",
    doc: "Maximum accepted password length.",
  },
  {
    name: "PASSWORD_REQUIRE_UPPERCASE",
    group: "Authentication",
    kind: "boolean",
    default: "true",
    doc: "Require at least one uppercase letter in passwords.",
  },
  {
    name: "PASSWORD_REQUIRE_LOWERCASE",
    group: "Authentication",
    kind: "boolean",
    default: "true",
    doc: "Require at least one lowercase letter in passwords.",
  },
  {
    name: "PASSWORD_REQUIRE_NUMBER",
    group: "Authentication",
    kind: "boolean",
    default: "true",
    doc: "Require at least one number in passwords.",
  },
  {
    name: "PASSWORD_REQUIRE_SYMBOL",
    group: "Authentication",
    kind: "boolean",
    default: "true",
    doc: "Require at least one symbol in passwords.",
  },
];
